-- MySQL Script generated by MySQL Workbench
-- Mon Jun  5 19:52:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flisol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flisol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flisol` ;
USE `flisol` ;

-- -----------------------------------------------------
-- Table `flisol`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol`.`Evento` (
  `idEvento` INT NOT NULL,
  `nombreEvento` VARCHAR(75) NOT NULL,
  `descripcionEvento` VARCHAR(100) NULL,
  `fechaEvento` DATE NOT NULL,
  PRIMARY KEY (`idEvento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `flisol`.`Asistente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flisol`.`Asistente` (
  `idAsistente` INT NOT NULL,
  `nombreAsistente` VARCHAR(45) NOT NULL,
  `paternoAsistente` VARCHAR(45) NOT NULL,
  `maternoAsistente` VARCHAR(45) NOT NULL,
  `emailAsistente` VARCHAR(45) NOT NULL,
  `idEvento` INT NOT NULL,
  PRIMARY KEY (`idAsistente`),
  INDEX `fk_Asistente_Evento_idx` (`idEvento` ASC) VISIBLE,
  CONSTRAINT `fk_Asistente_Evento`
    FOREIGN KEY (`idEvento`)
    REFERENCES `flisol`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
